# Generated by Django 2.0.2 on 2018-03-23 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_summoner_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Summoner_Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantId', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('championId', models.CharField(max_length=25)),
                ('win', models.BooleanField()),
                ('role', models.CharField(max_length=25)),
                ('lane', models.CharField(max_length=25)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Match')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Summoner')),
            ],
        ),
    ]
