# Generated by Django 2.0.2 on 2018-03-23 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_match_summoner_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gameCreation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='gameDuration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='gameId',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summoner',
            name='revisionDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='summoner_match',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
