# Generated by Django 2.0.2 on 2018-03-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180323_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='revisionDate',
            field=models.DateTimeField(),
        ),
    ]
