# Generated by Django 2.0.2 on 2018-03-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180323_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='gameCreation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='summoner_match',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
