# Generated by Django 2.0.2 on 2018-03-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180323_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='gameCreation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='revisionDate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='summoner_match',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
