# Generated by Django 2.0.2 on 2018-03-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180323_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='accountId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='summoner_match',
            name='championId',
            field=models.IntegerField(),
        ),
    ]
