# Generated by Django 2.0.2 on 2018-03-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180323_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='summonerId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
