# Generated by Django 2.0.2 on 2018-03-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_summoner_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='tier',
        ),
    ]
