# Generated by Django 2.0.2 on 2018-03-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180324_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner_match',
            name='summoner',
        ),
        migrations.AddField(
            model_name='summoner_match',
            name='summoner_accountId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
