# Generated by Django 2.0.2 on 2018-03-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180324_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner_match',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
