# Generated by Django 2.0.2 on 2018-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180324_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner_match',
            name='summoner_name',
            field=models.CharField(default='', max_length=18),
            preserve_default=False,
        ),
    ]
