# Generated by Django 2.0.2 on 2018-03-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_summoner_match_summoner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championId', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('locale', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=25)),
            ],
        ),
    ]
