# Generated by Django 2.0.2 on 2018-03-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180325_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='championId',
            field=models.CharField(max_length=10),
        ),
    ]
