# Generated by Django 2.0.2 on 2018-03-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180325_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner_match',
            name='championName',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
