# Generated by Django 2.0.2 on 2018-03-28 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueType', models.TextField()),
                ('rank', models.TextField()),
                ('leaguePoints', models.IntegerField()),
                ('miniSeries', models.TextField()),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Summoner')),
            ],
        ),
    ]
