# Generated by Django 2.0.2 on 2018-03-29 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_league_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='leagues_updated_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
