# Generated by Django 2.0.2 on 2018-03-31 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180330_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner_match',
            name='summoner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Summoner'),
            preserve_default=False,
        ),
    ]
